<?xml version="1.0"?>
<robot>

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> addObstacle
  <property name="eklavya_calib_cam_x" value="${-0.0844382+0.36-0.55}" />
  <property name="eklavya_calib_cam_y" value="${0+ 0}" />
  <property name="eklavya_calib_cam_z" value="${0.05+0.55-0.18}" />
  <property name="eklavya_calib_cam_rr" value="0" />
  <property name="eklavya_calib_cam_rp" value="0" />
  <property name="eklavya_calib_cam_ry" value="3.1415926535897932384626" />
<<<<<<< HEAD
=======
  <property name="eklavya_calib_cam_x" value="${-0.0844382+base_x_size/4}" />
  <property name="eklavya_calib_cam_y" value="${0+ 0}" />
  <property name="eklavya_calib_cam_z" value="${cam_pole+base_z_size}" />
  <property name="eklavya_calib_cam_rr" value="0" />
  <property name="eklavya_calib_cam_rp" value="${cam_angle}" />
  <property name="eklavya_calib_cam_ry" value="0" />
>>>>>>> 5b6c52d7db233097e1f897db6dcb4b9a52417cae
=======
>>>>>>> addObstacle
  <property name="eklavya_camera_parent_name" value="base_link" />

</robot>

