<?xml version="1.0"?>
<robot name="eklavya_hardware" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <!--All units in m-kg-s-radians unit system -->
    <property name="M_PI" value="3.1415926535897931" />

   
  <!-- Macro for eklavya body. Including Gazebo extensions, but does not include Kinect -->
  <include filename="$(find eklavya_description)/urdf/params.xacro"/>
  <include filename="$(find eklavya_description)/urdf/gazebo.urdf.xacro"/>
  <include filename="$(find eklavya_description)/urdf/materials.urdf.xacro"/>
  <include filename="$(find eklavya_description)/urdf/eklavya_hardware.xacro"/>
  <include filename="$(find eklavya_description)/urdf/eklavya_wheel.xacro"/>
  <include filename="$(find eklavya_description)/urdf/hokuyo_urg.xacro"/>
  <include filename="$(find eklavya_description)/urdf/sick_lms100_200.urdf.xacro"/>
  <include filename="$(find eklavya_description)/urdf/microstrain_3dmgx3_imu.urdf.xacro"/>
  <include filename="$(find eklavya_description)/urdf/eklavya_kinect.urdf.xacro"/>

    
  <xacro:macro name="eklavya_body">
    <!--Dummy base without INERTIA because base_link is not supposed to have inertia-->
    <!-- BASE-FOOTPRINT -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.01" />
        </geometry>
      </visual>
      <inertial>
            <mass value="0.0001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0" 
                izz="0.0001" />
        </inertial>
	<!--  <collision>
          <origin xyz="0 0 0.0" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
         </geometry>
      </collision>-->
    </link>
    <gazebo reference="base_footprint">
        <material>Gazebo/Green</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_x_size/2 - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link" />
    </joint>

    <!-- BASE-LINK -->
    <!--Actual body/chassis of the robot-->
    <link name="base_link">
	<box_inertial_with_origin x="${base_x_size}" y="${base_y_size}" z="${base_z_size}" mass="${base_mass}" origin="0 0 ${base_z_size/2}" />
      <visual>		  
        <eklavya_base_link_mesh>
           <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
           <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
        </eklavya_base_link_mesh>
      </visual>

      <collision>
         <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
         <geometry>
            <box size = "${base_x_size+0.02} ${base_y_size} ${base_z_size+0.02}"/>--> <!--making it slightly bigger in x and z direction-->
         </geometry>
      </collision>
    </link>
    <gazebo_eklavya_base_link_surface />


	 <!-- WHEEL macros -->
    <eklavya_wheel suffix="left" parent="base_link">
      <origin xyz="${-1*base_x_origin_to_wheel_origin} ${-1*base_y_origin_to_wheel_origin} ${ -1*base_z_origin_to_wheel_origin}" rpy="${M_PI} 0 0" /> 
    </eklavya_wheel>
   
    <eklavya_wheel suffix="right" parent="base_link">
      <origin xyz="${-1*base_x_origin_to_wheel_origin} ${base_y_origin_to_wheel_origin} ${ -1*base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    </eklavya_wheel>  

    
    <!-- Castor -->    
	<caster_support_hinge suffix="front" parent="base_link" />
    <caster_wheel suffix="front" parent="base_link" />   

	<!-- Controllers -->
	<!--<gazebo_eklavya_simple_drive_plugin />-->
	<!--<gazebo_eklavya_drive_plugin /> -->
	   <gazebo_eklavya_drive_plugin_diffdrive />  <!-- cmd_vel movement -->
	 <!-- <gazebo_eklavya_p3d_plugin />--> <!-- Ground Truth-->
	 <!-- <eklavya_controllers_common /> -->
    
    <!-- Simulation sensors -->
   <!-- <hokuyo_urg name="hokuyo_laser" parent="base_link" >
      <origin rpy="0 0 ${M_PI}" xyz="${-base_x_size/2} 0  0.33"/>
    </hokuyo_urg> -->
    
	<!--<sick_lms100_200 name="sick_laser" parent="base_link" >
		<origin rpy="0 0 0" xyz="${base_x_size/2+0.12} 0  0.080"/>
	</sick_lms100_200>   -->
	<!-- <microstrain_imu name="eklavya_sim_imu" parent="base_link" imu_topic="imu/data" update_rate="30" stdevNoise="0.0017">
		 <origin rpy="0 0 0" xyz="0 0 0"/>
	</microstrain_imu> -->
    <!-- Kinect frames and mounting (includes simulation) -->
   <!-- <eklavya_kinect> -->
	  <!--origin rpy="0 0 ${M_PI/2}" xyz="${-base_x_size/2-0.05} 0  0.6"/-->
	<!--</eklavya_kinect> -->
  </xacro:macro>
</robot>

