<?xml version="1.0"?>
<robot>

  <property name="eklavya_calib_cam_x" value="${-0.0844382+base_x_size/4}" />
  <property name="eklavya_calib_cam_y" value="${0+ 0}" />
  <property name="eklavya_calib_cam_z" value="${cam_pole+base_z_size}" />
  <property name="eklavya_calib_cam_rr" value="0" />
  <property name="eklavya_calib_cam_rp" value="${cam_angle}" />
  <property name="eklavya_calib_cam_ry" value="0" />
  <property name="eklavya_camera_parent_name" value="base_link" />

</robot>

