<?xml version="1.0"?>

<robot
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    <include filename="$(find eklavya_description)/urdf/params.xacro"/>  

 
 
 <macro name="caster_support_hinge" params="suffix parent"> 
	<joint name="${parent}_caster_support_hinge_${suffix}_joint" type="continuous">
      <origin  rpy="0 0 0" xyz="${-base_x_size/2 +wheelhub_x_size/2} 0 ${castor_x_size/2 -wheel_x_size/2 -base_z_origin_to_caster_wheel_origin}"/> 
      <parent link="${parent}" />
      <child link="${parent}_caster_support_hinge_${suffix}_link"/>

      <axis xyz="0 0 1" />
      <anchor xyz="0.01 0 0" />
      <limit effort="100" velocity="100" k_velocity="0" />
      <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <transmission type="pr2_mechanism_model/SimpleTransmission" name="base_caster_support_trans">
      <actuator name="${parent}_caster_support_hinge_${suffix}_motor" />
      <joint name="${parent}_caster_support_hinge_${suffix}_joint" />
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>

    <link name="${parent}_caster_support_hinge_${suffix}_link">
      <inertial>
			<mass value="0.1"/>
			<origin xyz="0 0 0" />
			<inertia ixx="0.01" ixy="0.0" ixz="0.0"
					 iyy="0.01" iyz="0.0"
					 izz="0.01" />
		</inertial>
      <visual>
        <eklavya_castor_support_link_mesh />        
      </visual>
      <collision>
        <!--<eklavya_collision_none />-->
        <eklavya_castor_support_link_mesh />  
      </collision>
    </link>
</macro>
	
<macro name="caster_wheel" params="suffix parent">
	  
	 <joint name="${parent}_caster_wheel_${suffix}_joint" type="continuous">
      <origin rpy="0 0 0" xyz="${base_x_origin_to_caster_wheel_origin} ${base_y_origin_to_caster_wheel_origin} ${base_z_origin_to_caster_wheel_origin} " />
      <parent link="${parent}_caster_support_hinge_${suffix}_link" />
      <child link="${parent}_caster_wheel_${suffix}_link" />

      <axis xyz="0 1 0" />
      <anchor xyz="0 0 0" />
      <limit effort="100" velocity="100" k_velocity="0" />
      <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <transmission type="pr2_mechanism_model/SimpleTransmission" name="caster_wheel_trans">
      <actuator name="${parent}_caster_wheel_${suffix}_motor" />
      <joint name="${parent}_caster_wheel_${suffix}_joint" />
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>

    <link name="${parent}_caster_wheel_${suffix}_link">
    
	<!--<cylinder_inertial_with_origin_wheel radius="${castor_x_size/2}" length="${castor_z_size}" mass="1" origin="0 0 0" /> -->
	 <inertial>
		<mass value="0.1" /> 
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
				  iyy="0.015218160428" iyz="-0.000004273467"
				  izz="0.011763977943" />
	</inertial>
      <visual>
        <eklavya_castor_wheel_link_mesh />
      </visual>

      <collision>
		<eklavya_castor_wheel_link_mesh />
		<!--
		<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
		<geometry>   
			<cylinder radius="${castor_x_size/2}" length="${castor_z_size}"/>
		</geometry> -->
      </collision>
    </link>
    <gazebo_eklavya_castor_wheel_link_surface suffix="${suffix}" parent="${parent}" />
</macro>

</robot>
